name: Run tests w/o GPU

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  cpu_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1']
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }} (w/o GPU)
    steps:
      - uses: actions/checkout@v2
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Set up ~/.julia/registries/General as a Git repository (using julia-buildpkg)
        uses: julia-actions/julia-buildpkg@v1
      - run: julia -e 'using Pkg; pkg"add Run@0.1"'
      - run: julia -e 'using Run; Run.prepare("test/environments/main")'
      - run: julia -e 'using Run; Run.test(project="test/environments/main")'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: cpu
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
